### ISSUE TITLE
This works amazing thanks!

### ISSUE THREAD

**Issue by a10kiloham** [mdesilva/DocSendDownloader#1]
Just wanted to drop you a note this is awesome, thanks for sharing!

**Comment by mdesilva** [comment]
Thanks ! If you don't mind, leave a review here:
https://chrome.google.com/webstore/detail/docsend-slide-deck-downlo/bdapagnogpjnojnencohaeeeedhoncjf

**Comment by a10kiloham** [comment]
They disabled reviews sadly because of covid :(
