### ISSUE TITLE
No longer supported by Chrome

### ISSUE THREAD

**Issue by DavidWilkens** [mdesilva/DocSendDownloader#13]
When I opened Chrome this morning, it informed me that this extension is no longer supported.  Any suggestions?

**Comment by uxduck** [comment]
It still works. It's just a warning because Chrome wants to deprecate this style of extension, because they want to limit the power of extensions (primarily to destroy the ability of adblocking extensions).

**Comment by DavidWilkens** [comment]
I noticed a couple a days ago that it started to work again.  Thanks
