### ISSUE TITLE
New version on Chrome store seems to hang

### ISSUE THREAD

**Issue by a10kiloham** [mdesilva/DocSendDownloader#3]
goes very slow all the sudden and in my case hangs repeatedly on p 4 of a 23 page preso. :(

**Comment by a10kiloham** [comment]
this is the new Chrome Extension pushed today I think. not sideloaded via github.

**Comment by mdesilva** [comment]
What is the link to the presentation you are downloading, and where are you downloading it from ?

**Comment by a10kiloham** [comment]
it's a private link - how can I send you that best?

**Comment by a10kiloham** [comment]
downloading via Chrome using the official extension

**Comment by a10kiloham** [comment]
ah just saw your profile link so emailed it to you directly. testing w/ a few they all seem to have this same hanging now.

**Comment by mdesilva** [comment]
Removed CORS proxy from version 1.6. Download speeds now completely dependent on client's connection.
