### ISSUE TITLE
Exception on unrecognized image format due to access denied error

### ISSUE THREAD

**Issue by ericu** [mdesilva/DocSendDownloader#6]
I'm getting a failure here:

open (pdfkit.js:4419)
openImage (pdfkit.js:4549)
(anonymous) (GeneratePDF.js:26)
Promise.then (async)
addSlidesToPDF (GeneratePDF.js:25)
buildPdf (GeneratePDF.js:36)
generateSlideDeckPdf (DocSendDownloader.js:34)

In openImage, src is data:text/xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48RXJyb3I+PENvZGU+QWNjZXNzRGVuaWVkPC9Db2RlPjxNZXNzYWdlPkFjY2VzcyBkZW5pZWQ8L01lc3NhZ2U+PC9FcnJvcj4=

Which appears to be the encoding of "<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access denied</Message></Error>"

I'm viewing the file fine in the browser; I don't know why you're getting that error.  I can't see where that string came from [I guess the Chrome dev tools don't handle all async function closure variables], but when I dump out slideImageUrls all 326 of them are of this form:
https://d2qvtfnm75xrxf.cloudfront.net/docs%2F[lots of params here I've trimmed out]

I've downloaded several other files before and after this, but this one is huge, and the others were all under about 20 pages.  Let me know if I can help you debug this.

**Comment by mdesilva** [comment]
Can you please provide a link to the slides you were attempting to download ?

**Comment by ericu** [comment]
Sorry--the whole reason they were in docsend is that the person who put them up doesn't want them shared, of course.
