### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by joesixpack** [mdesilva/DocSendDownloader#7]
![image](https://user-images.githubusercontent.com/23145642/193899337-afa08702-8e5c-4b4a-8db3-16132fce8d24.png)

Maybe need Dropbox in site access?  It's locked, so is all sites.

**Comment by mdesilva** [comment]
What is the new URL of the Dropbox Docsend platform ? You don't need to share an exact link to a document, just the base url (the part of the url before the TLD (e.g .com))

**Comment by joesixpack** [comment]
Base URL is still like: https://docsend.com/view/xxxxx

**Comment by mdesilva** [comment]
It should not be locked on that site then; it should work on any **docsend.com** page. Are you still experiencing the issue ? Is it on all documents or just a particular one ?

**Comment by joesixpack** [comment]
It seems to be all documents now.  I've yet to see a download bar again.  I'm using Brave.

**Comment by joesixpack** [comment]
Could you provide a debug version that enable access to all sites to see if that resolves it?

**Comment by mdesilva** [comment]
@joesixpack I just tried two different documents on Brave browser and I was able to generate slide decks for both of them using the extension.

**Comment by mdesilva** [comment]
If you want a debug version, you can just clone this repo to your computer and modify `manifest.json` to enable access to all sites.
